# Generated by Django 5.0.7 on 2025-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0013_alter_volunteeropportunity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
